### PR TITLE
Creating new note & contact page UI

### LINKED ISSUE #3: Create new task UI

### PR DESCRIPTION
**Pull request by JhumurChatterjee**
Fixes #3 

  - Modified new note page UI according to the design provided in [Figma](https://www.figma.com/file/1iyrPubCxGZUqEt3t6kNSa/NeetoHelp?node-id=7449%3A27625&viewport=354%2C254%2C0.299105167388916).
  - Added new contact page UI according to the design provided in [Figma](https://www.figma.com/file/1iyrPubCxGZUqEt3t6kNSa/NeetoHelp?node-id=7449%3A27625&viewport=354%2C254%2C0.299105167388916).

### CODE REVIEW

**Comment by kabir4691** [comment]
@JhumurChatterjee Mention issue number this PR closes in the description.

**Comment by kabir4691** [comment]
@JhumurChatterjee Please fix PR details according to our discussion.

**Comment by JhumurChatterjee** [comment]
@kabir4691 I have changed the details. Please have a look.

**Comment by kabir4691** [comment]
@JhumurChatterjee Link the issue manually, if linking by comment doesn't work.

**Comment by JhumurChatterjee** [comment]
@kabir4691 Linked the issue manually.

**Pull request merged**
